/** Generated by scripts/gen_admin_mock.py from tests/test_metrics.py. Do not edit by hand. */
import type { AdminMetrics } from "./types";

export const ADMIN_METRICS_FIXTURE: AdminMetrics = {
  range: {
    start: 1790654400.0,
    end: 1791259200.0,
    now: 1790870400.0,
    start_day: "2026-09-29",
    end_day: "2026-10-01",
  },
  today: {
    current: {
      revenue_cents: 2998,
      new_buyers: 2,
      signups: 6,
      leagues_linked: 3,
      spend_cents: 5500,
      cac_cents: 2750,
      paying_now: 3,
    },
    previous: {
      revenue_cents: 499,
      new_buyers: 1,
      signups: 1,
      leagues_linked: 0,
      spend_cents: 999,
      cac_cents: 999,
    },
    last_hour: {
      signups: 1,
      checkouts: 0,
      purchases: 0,
    },
  },
  funnel: {
    steps: [
      {
        key: "landing_signup",
        num: 4,
        den: 10,
        rate: 0.4,
        healthy: 0.15,
        leak: 0.08,
        status: "healthy",
        scope: "range",
      },
      {
        key: "signup_linked",
        num: 3,
        den: 6,
        rate: 0.5,
        healthy: 0.7,
        leak: 0.5,
        status: "watch",
        scope: "range",
      },
      {
        key: "linked_paid_7d",
        num: 2,
        den: 3,
        rate: 0.6666666666666666,
        healthy: 0.05,
        leak: 0.02,
        status: "healthy",
        scope: "range",
      },
      {
        key: "week_retained",
        num: 1,
        den: 1,
        rate: 1.0,
        healthy: 0.5,
        leak: 0.3,
        status: "healthy",
        scope: "to_date",
      },
    ],
    paywall: [
      {
        feature: "waivers",
        views: 2,
      },
      {
        feature: "trade_lab",
        views: 1,
      },
    ],
    checkout: {
      started: 3,
      finished: 2,
      abandoned: 1,
      finish_rate: 0.6666666666666666,
    },
  },
  channels: {
    rows: [
      {
        source: "google",
        visitors: 2,
        signups: 1,
        linked: 1,
        buyers: 1,
        revenue_cents: 2499,
        spend_cents: 500,
        cac_cents: 500,
        verdict: "scale",
        campaigns: [
          {
            campaign: "(none)",
            signups: 1,
            buyers: 1,
            revenue_cents: 2499,
          },
        ],
      },
      {
        source: "reddit",
        visitors: 5,
        signups: 2,
        linked: 2,
        buyers: 1,
        revenue_cents: 499,
        spend_cents: 3000,
        cac_cents: 3000,
        verdict: "watch",
        campaigns: [
          {
            campaign: "wk4 · hookA",
            signups: 1,
            buyers: 1,
            revenue_cents: 499,
          },
          {
            campaign: "(none)",
            signups: 1,
            buyers: 0,
            revenue_cents: 0,
          },
        ],
      },
      {
        source: "direct",
        visitors: 3,
        signups: 2,
        linked: 0,
        buyers: 1,
        revenue_cents: 499,
        spend_cents: 0,
        cac_cents: null,
        verdict: "organic",
        campaigns: [
          {
            campaign: "(none)",
            signups: 2,
            buyers: 1,
            revenue_cents: 499,
          },
        ],
      },
      {
        source: "share",
        visitors: 0,
        signups: 1,
        linked: 0,
        buyers: 0,
        revenue_cents: 0,
        spend_cents: 0,
        cac_cents: null,
        verdict: "organic",
        campaigns: [
          {
            campaign: "(none)",
            signups: 1,
            buyers: 0,
            revenue_cents: 0,
          },
        ],
      },
      {
        source: "meta",
        visitors: 0,
        signups: 0,
        linked: 0,
        buyers: 0,
        revenue_cents: 0,
        spend_cents: 2000,
        cac_cents: null,
        verdict: "kill",
        campaigns: [],
      },
    ],
    spend: [
      {
        id: "1",
        day: "2026-09-29",
        channel: "reddit",
        campaign: "",
        cents: 3000,
        clicks: 100,
        note: "",
      },
      {
        id: "2",
        day: "2026-09-30",
        channel: "google",
        campaign: "",
        cents: 500,
        clicks: 20,
        note: "",
      },
      {
        id: "3",
        day: "2026-10-01",
        channel: "meta",
        campaign: "",
        cents: 2000,
        clicks: 50,
        note: "",
      },
    ],
  },
  revenue: {
    by_day: [
      {
        day: "2026-09-29",
        by_sku: {
          week_pass: 499,
          full_report: 2499,
        },
        total_cents: 2998,
      },
      {
        day: "2026-09-30",
        by_sku: {
          week_pass: 499,
        },
        total_cents: 499,
      },
      {
        day: "2026-10-01",
        by_sku: {},
        total_cents: 0,
      },
      {
        day: "2026-10-02",
        by_sku: {},
        total_cents: 0,
      },
      {
        day: "2026-10-03",
        by_sku: {},
        total_cents: 0,
      },
      {
        day: "2026-10-04",
        by_sku: {},
        total_cents: 0,
      },
      {
        day: "2026-10-05",
        by_sku: {},
        total_cents: 0,
      },
    ],
    gross_cents: 3497,
    refunds_cents: 499,
    net_cents: 2998,
    net_after_fees_cents: 2807,
    payments: 3,
    subscriptions: {
      started: 1,
      renewals: 1,
      cancelled: 0,
      upgraded: 0,
    },
  },
  retention: {
    all: [
      {
        week_of: "2026-09-22",
        size: 1,
        cells: [1.0, 1.0],
      },
      {
        week_of: "2026-09-29",
        size: 6,
        cells: [0.3333333333333333],
      },
    ],
    paying: [
      {
        week_of: "2026-09-22",
        size: 1,
        cells: [1.0, 1.0],
      },
      {
        week_of: "2026-09-29",
        size: 2,
        cells: [0.5],
      },
    ],
  },
  loop: {
    created: 2,
    opens: 5,
    opens_per_card: 2.5,
    signups: 1,
    buyers: 0,
    top: [
      {
        id: "ab3kx9qz",
        views: 5,
        created: 1790654400.0,
      },
    ],
  },
  thresholds: {
    target_cac_cents: 800,
    kill_spend_cents: 1600,
    funnel: {
      landing_signup: {
        healthy: 0.15,
        leak: 0.08,
      },
      signup_linked: {
        healthy: 0.7,
        leak: 0.5,
      },
      linked_paid_7d: {
        healthy: 0.05,
        leak: 0.02,
      },
      week_retained: {
        healthy: 0.5,
        leak: 0.3,
      },
    },
  },
};
