/** Generated by scripts/gen_battle_mock.py from the recorded fixtures. Do not edit by hand. */
import type { Battle } from "./types";

export const BATTLE_FIXTURE: Battle = {
  "week": 2,
  "spot": "WR2",
  "a": {
    "id": "7525",
    "name": "DeVonta Smith",
    "position": "WR",
    "nfl_team": "PHI",
    "photo": "https://sleepercdn.com/content/nfl/players/thumb/7525.jpg",
    "team_logo": "https://sleepercdn.com/images/team_logos/nfl/phi.png",
    "injury_status": null,
    "projected": 12.34,
    "ros": 167.0,
    "where": {
      "kind": "starter",
      "slot": "WR",
      "label": "WR2",
      "team_name": null
    },
    "injury_body_part": null,
    "bye_week": 10,
    "slate": [
      {
        "week": 2,
        "opp": "TEN",
        "home": false,
        "bye": false,
        "rank": 15,
        "of": 32
      },
      {
        "week": 3,
        "opp": "CHI",
        "home": false,
        "bye": false,
        "rank": 30,
        "of": 32
      },
      {
        "week": 4,
        "opp": "LAR",
        "home": true,
        "bye": false,
        "rank": 31,
        "of": 32
      },
      {
        "week": 5,
        "opp": "JAX",
        "home": false,
        "bye": false,
        "rank": 19,
        "of": 32
      },
      {
        "week": 6,
        "opp": "CAR",
        "home": true,
        "bye": false,
        "rank": 20,
        "of": 32
      },
      {
        "week": 7,
        "opp": "DAL",
        "home": true,
        "bye": false,
        "rank": 8,
        "of": 32
      },
      {
        "week": 8,
        "opp": "WAS",
        "home": false,
        "bye": false,
        "rank": 16,
        "of": 32
      },
      {
        "week": 9,
        "opp": "NYG",
        "home": true,
        "bye": false,
        "rank": 14,
        "of": 32
      },
      {
        "week": 10,
        "opp": null,
        "home": null,
        "bye": true,
        "rank": null,
        "of": null
      },
      {
        "week": 11,
        "opp": "PIT",
        "home": true,
        "bye": false,
        "rank": 1,
        "of": 32
      },
      {
        "week": 12,
        "opp": "DAL",
        "home": false,
        "bye": false,
        "rank": 8,
        "of": 32
      },
      {
        "week": 13,
        "opp": "ARI",
        "home": false,
        "bye": false,
        "rank": 17,
        "of": 32
      },
      {
        "week": 14,
        "opp": "IND",
        "home": true,
        "bye": false,
        "rank": 21,
        "of": 32
      },
      {
        "week": 15,
        "opp": "SEA",
        "home": true,
        "bye": false,
        "rank": 7,
        "of": 32
      },
      {
        "week": 16,
        "opp": "HOU",
        "home": true,
        "bye": false,
        "rank": 23,
        "of": 32
      },
      {
        "week": 17,
        "opp": "SF",
        "home": false,
        "bye": false,
        "rank": 6,
        "of": 32
      }
    ],
    "opp": "@ TEN"
  },
  "b": {
    "id": "8134",
    "name": "Khalil Shakir",
    "position": "WR",
    "nfl_team": "BUF",
    "photo": "https://sleepercdn.com/content/nfl/players/thumb/8134.jpg",
    "team_logo": "https://sleepercdn.com/images/team_logos/nfl/buf.png",
    "injury_status": null,
    "projected": 8.67,
    "ros": 119.5,
    "where": {
      "kind": "wire",
      "slot": null,
      "label": "Free agent",
      "team_name": null
    },
    "injury_body_part": null,
    "bye_week": 7,
    "slate": [
      {
        "week": 2,
        "opp": "DET",
        "home": true,
        "bye": false,
        "rank": 29,
        "of": 32
      },
      {
        "week": 3,
        "opp": "LAC",
        "home": true,
        "bye": false,
        "rank": 18,
        "of": 32
      },
      {
        "week": 4,
        "opp": "NE",
        "home": true,
        "bye": false,
        "rank": 24,
        "of": 32
      },
      {
        "week": 5,
        "opp": "LAR",
        "home": false,
        "bye": false,
        "rank": 31,
        "of": 32
      },
      {
        "week": 6,
        "opp": "LV",
        "home": false,
        "bye": false,
        "rank": 12,
        "of": 32
      },
      {
        "week": 7,
        "opp": null,
        "home": null,
        "bye": true,
        "rank": null,
        "of": null
      },
      {
        "week": 8,
        "opp": "BAL",
        "home": true,
        "bye": false,
        "rank": 11,
        "of": 32
      },
      {
        "week": 9,
        "opp": "MIN",
        "home": false,
        "bye": false,
        "rank": 32,
        "of": 32
      },
      {
        "week": 10,
        "opp": "NYJ",
        "home": false,
        "bye": false,
        "rank": 4,
        "of": 32
      },
      {
        "week": 11,
        "opp": "MIA",
        "home": true,
        "bye": false,
        "rank": 10,
        "of": 32
      },
      {
        "week": 12,
        "opp": "KC",
        "home": true,
        "bye": false,
        "rank": 2,
        "of": 32
      },
      {
        "week": 13,
        "opp": "NE",
        "home": false,
        "bye": false,
        "rank": 24,
        "of": 32
      },
      {
        "week": 14,
        "opp": "GB",
        "home": false,
        "bye": false,
        "rank": 22,
        "of": 32
      },
      {
        "week": 15,
        "opp": "CHI",
        "home": true,
        "bye": false,
        "rank": 30,
        "of": 32
      },
      {
        "week": 16,
        "opp": "DEN",
        "home": false,
        "bye": false,
        "rank": 5,
        "of": 32
      },
      {
        "week": 17,
        "opp": "MIA",
        "home": false,
        "bye": false,
        "rank": 10,
        "of": 32
      }
    ],
    "opp": "vs DET"
  },
  "horizons": [
    {
      "key": "week",
      "first": 2,
      "last": 2,
      "a": 12.3,
      "b": 8.7,
      "a_games": null,
      "b_games": null,
      "winner": "a",
      "strength": "Lean",
      "p": 0.655,
      "tipped": false,
      "held": false,
      "factors": [
        {
          "key": "stack",
          "favors": "sit",
          "line": "DeVonta Smith stacks with your RB Saquon Barkley"
        },
        {
          "key": "opponent",
          "favors": "sit",
          "line": "DeVonta Smith faces TEN, 15th of 32 against the WR; Khalil Shakir faces DET, 29th of 32 (1 game in)"
        },
        {
          "key": "rest",
          "favors": "start",
          "line": "DeVonta Smith had a full week; Khalil Shakir plays Thursday on 4 days\u2019 rest"
        },
        {
          "key": "role",
          "favors": "sit",
          "line": "DJ Moore is Out ahead of Khalil Shakir: the targets open up"
        }
      ],
      "tilt": -2,
      "state": "pre",
      "a_state": "pre",
      "b_state": "pre",
      "a_points": null,
      "b_points": null
    },
    {
      "key": "next5",
      "first": 2,
      "last": 6,
      "a": 55.7,
      "b": 39.8,
      "a_games": 5,
      "b_games": 5,
      "winner": "a",
      "strength": "clear",
      "p": null,
      "tipped": false,
      "held": false,
      "sos_a": 23.0,
      "sos_b": 22.8,
      "assumed": false
    },
    {
      "key": "ros",
      "first": 2,
      "last": 17,
      "a": 167.0,
      "b": 119.5,
      "a_games": 15,
      "b_games": 15,
      "winner": "a",
      "strength": "clear",
      "p": null,
      "tipped": false,
      "held": false,
      "sos_a": 15.7,
      "sos_b": 17.6,
      "assumed": false
    },
    {
      "key": "playoffs",
      "first": 15,
      "last": 17,
      "a": 33.4,
      "b": 23.9,
      "a_games": 3,
      "b_games": 3,
      "winner": "a",
      "strength": "clear",
      "p": null,
      "tipped": false,
      "held": false,
      "sos_a": 12.0,
      "sos_b": 15.0,
      "assumed": true
    }
  ],
  "headline": {
    "kind": "sweep",
    "winner": "a",
    "a": 4,
    "b": 0,
    "now": "a",
    "later": "a"
  },
  "tape": [
    {
      "key": "proj_week",
      "family": "outlook",
      "a": {
        "v": 12.34,
        "text": "12.3",
        "sub": null
      },
      "b": {
        "v": 8.67,
        "text": "8.7",
        "sub": null
      },
      "edge": "a"
    },
    {
      "key": "rank_week",
      "family": "outlook",
      "a": {
        "v": 11.0,
        "text": "WR11",
        "sub": "of 99"
      },
      "b": {
        "v": 37.0,
        "text": "WR37",
        "sub": "of 99"
      },
      "edge": "a"
    },
    {
      "key": "proj_next5",
      "family": "outlook",
      "a": {
        "v": 55.7,
        "text": "55.7",
        "sub": "5 games"
      },
      "b": {
        "v": 39.8,
        "text": "39.8",
        "sub": "5 games"
      },
      "edge": "a"
    },
    {
      "key": "proj_ros",
      "family": "outlook",
      "a": {
        "v": 167.0,
        "text": "167",
        "sub": "15 games"
      },
      "b": {
        "v": 119.5,
        "text": "119.5",
        "sub": "15 games"
      },
      "edge": "a"
    },
    {
      "key": "proj_playoffs",
      "family": "outlook",
      "a": {
        "v": 33.4,
        "text": "33.4",
        "sub": "3 games"
      },
      "b": {
        "v": 23.9,
        "text": "23.9",
        "sub": "3 games"
      },
      "edge": "a"
    },
    {
      "key": "rank_ros",
      "family": "outlook",
      "a": {
        "v": 12.0,
        "text": "WR12",
        "sub": "of 99"
      },
      "b": {
        "v": 48.0,
        "text": "WR48",
        "sub": "of 99"
      },
      "edge": "a"
    },
    {
      "key": "rate_ros",
      "family": "outlook",
      "a": {
        "v": 11.133333333333333,
        "text": "11.1",
        "sub": null
      },
      "b": {
        "v": 7.966666666666667,
        "text": "8",
        "sub": null
      },
      "edge": "a"
    },
    {
      "key": "rank_season",
      "family": "season",
      "a": {
        "v": 41.0,
        "text": "WR41",
        "sub": "of 97"
      },
      "b": {
        "v": 40.0,
        "text": "WR40",
        "sub": "of 97"
      },
      "edge": null
    },
    {
      "key": "ppg",
      "family": "season",
      "a": {
        "v": 6.8,
        "text": "6.8",
        "sub": "1 game"
      },
      "b": {
        "v": 7.0,
        "text": "7",
        "sub": "1 game"
      },
      "edge": null
    },
    {
      "key": "points",
      "family": "season",
      "a": {
        "v": 6.8,
        "text": "6.8",
        "sub": null
      },
      "b": {
        "v": 7.0,
        "text": "7",
        "sub": null
      },
      "edge": null
    },
    {
      "key": "last_game",
      "family": "season",
      "a": {
        "v": 6.8,
        "text": "6.8",
        "sub": "wk 1 \u00b7 WR41"
      },
      "b": {
        "v": 7.0,
        "text": "7",
        "sub": "wk 1 \u00b7 WR40"
      },
      "edge": null
    },
    {
      "key": "form",
      "family": "season",
      "a": {
        "v": 6.8,
        "text": "6.8",
        "sub": "1 game"
      },
      "b": {
        "v": 7.0,
        "text": "7",
        "sub": "1 game"
      },
      "edge": null
    },
    {
      "key": "last_season",
      "family": "season",
      "a": {
        "v": 9.72,
        "text": "9.7",
        "sub": "17 games"
      },
      "b": {
        "v": 8.41,
        "text": "8.4",
        "sub": "16 games"
      },
      "edge": "a"
    },
    {
      "key": "snap",
      "family": "usage",
      "a": {
        "v": 0.945,
        "text": "94%",
        "sub": null
      },
      "b": {
        "v": 0.534,
        "text": "53%",
        "sub": null
      },
      "edge": "a"
    },
    {
      "key": "target_share",
      "family": "usage",
      "a": {
        "v": 0.286,
        "text": "29%",
        "sub": null
      },
      "b": {
        "v": 0.24,
        "text": "24%",
        "sub": null
      },
      "edge": "a"
    },
    {
      "key": "touches",
      "family": "usage",
      "a": {
        "v": 6.0,
        "text": "6",
        "sub": null
      },
      "b": {
        "v": 6.0,
        "text": "6",
        "sub": null
      },
      "edge": null
    },
    {
      "key": "red_zone",
      "family": "usage",
      "a": {
        "v": 0.0,
        "text": "0",
        "sub": null
      },
      "b": {
        "v": 3.0,
        "text": "3",
        "sub": null
      },
      "edge": "b"
    },
    {
      "key": "depth",
      "family": "usage",
      "a": {
        "v": 1.0,
        "text": "Starter",
        "sub": "LWR 1"
      },
      "b": {
        "v": 2.0,
        "text": "Backup",
        "sub": "SWR 2"
      },
      "edge": "a"
    },
    {
      "key": "start_weeks",
      "family": "risk",
      "a": {
        "v": 0.0,
        "text": "0 of 1",
        "sub": "top 36"
      },
      "b": {
        "v": 0.0,
        "text": "0 of 1",
        "sub": "top 36"
      },
      "edge": null
    },
    {
      "key": "boom_weeks",
      "family": "risk",
      "a": {
        "v": 0.0,
        "text": "0 of 1",
        "sub": "top 12"
      },
      "b": {
        "v": 0.0,
        "text": "0 of 1",
        "sub": "top 12"
      },
      "edge": null
    },
    {
      "key": "availability",
      "family": "risk",
      "a": {
        "v": 1.0,
        "text": "1 of 1",
        "sub": "17 of 17 last year"
      },
      "b": {
        "v": 0.9444444444444444,
        "text": "1 of 1",
        "sub": "16 of 17 last year"
      },
      "edge": null
    },
    {
      "key": "health",
      "family": "risk",
      "a": {
        "v": 2.0,
        "text": "Clear",
        "sub": null
      },
      "b": {
        "v": 2.0,
        "text": "Clear",
        "sub": null
      },
      "edge": null
    },
    {
      "key": "matchup",
      "family": "schedule",
      "a": {
        "v": 15.0,
        "text": "Average",
        "sub": "@ TEN \u00b7 15th/32"
      },
      "b": {
        "v": 29.0,
        "text": "Soft",
        "sub": "vs DET \u00b7 29th/32"
      },
      "edge": "b"
    },
    {
      "key": "sos_next5",
      "family": "schedule",
      "a": {
        "v": 23.0,
        "text": "Soft",
        "sub": "avg 23rd \u00b7 5 games"
      },
      "b": {
        "v": 22.8,
        "text": "Soft",
        "sub": "avg 23rd \u00b7 5 games"
      },
      "edge": null
    },
    {
      "key": "sos_ros",
      "family": "schedule",
      "a": {
        "v": 15.7,
        "text": "Average",
        "sub": "avg 16th \u00b7 15 games"
      },
      "b": {
        "v": 17.6,
        "text": "Average",
        "sub": "avg 18th \u00b7 15 games"
      },
      "edge": null
    },
    {
      "key": "sos_playoffs",
      "family": "schedule",
      "a": {
        "v": 12.0,
        "text": "Average",
        "sub": "avg 12th \u00b7 3 games"
      },
      "b": {
        "v": 15.0,
        "text": "Average",
        "sub": "avg 15th \u00b7 3 games"
      },
      "edge": null
    },
    {
      "key": "bye",
      "family": "schedule",
      "a": {
        "v": 10.0,
        "text": "Wk 10",
        "sub": null
      },
      "b": {
        "v": 7.0,
        "text": "Wk 7",
        "sub": null
      },
      "edge": null
    },
    {
      "key": "rest",
      "family": "schedule",
      "a": {
        "v": 6.0,
        "text": "Full week",
        "sub": "6 days"
      },
      "b": {
        "v": 4.0,
        "text": "Short week",
        "sub": "4 days"
      },
      "edge": "a"
    },
    {
      "key": "qb",
      "family": "situation",
      "a": {
        "v": 34.8,
        "text": "Hurts",
        "sub": "34.8 pts/g"
      },
      "b": {
        "v": 44.3,
        "text": "Allen",
        "sub": "44.3 pts/g"
      },
      "edge": "b"
    },
    {
      "key": "sacks",
      "family": "situation",
      "a": {
        "v": 3.0,
        "text": "3",
        "sub": "21st of 32"
      },
      "b": {
        "v": 2.0,
        "text": "2",
        "sub": "13th of 32"
      },
      "edge": "b"
    },
    {
      "key": "run_game",
      "family": "situation",
      "a": {
        "v": 5.74,
        "text": "5.7",
        "sub": "4th of 32"
      },
      "b": {
        "v": 4.15,
        "text": "4.2",
        "sub": "14th of 32"
      },
      "edge": "a"
    },
    {
      "key": "line_hurt",
      "family": "situation",
      "a": {
        "v": 2.0,
        "text": "2",
        "sub": null
      },
      "b": {
        "v": 1.0,
        "text": "1",
        "sub": null
      },
      "edge": "b"
    },
    {
      "key": "around",
      "family": "situation",
      "a": {
        "v": 0.0,
        "text": "Clear",
        "sub": null
      },
      "b": {
        "v": 1.0,
        "text": "Opening",
        "sub": "Moore Out"
      },
      "edge": "b"
    },
    {
      "key": "team_change",
      "family": "situation",
      "a": {
        "v": null,
        "text": "Same team",
        "sub": "PHI"
      },
      "b": {
        "v": null,
        "text": "Same team",
        "sub": "BUF"
      },
      "edge": null
    },
    {
      "key": "experience",
      "family": "situation",
      "a": {
        "v": 5.0,
        "text": "Year 6",
        "sub": "age 27"
      },
      "b": {
        "v": 4.0,
        "text": "Year 5",
        "sub": "age 26"
      },
      "edge": null
    },
    {
      "key": "handcuff",
      "family": "depth",
      "a": {
        "v": null,
        "text": "Moore",
        "sub": "OUT \u00b7 unrostered",
        "id": "7596",
        "owned": "none"
      },
      "b": {
        "v": null,
        "text": "Bell",
        "sub": "OUT \u00b7 unrostered",
        "id": "13402",
        "owned": "none"
      },
      "edge": null
    }
  ],
  "tally": {
    "total": {
      "a": 13,
      "b": 6,
      "rows": 36
    },
    "families": {
      "outlook": {
        "a": 7,
        "b": 0,
        "rows": 7
      },
      "season": {
        "a": 1,
        "b": 0,
        "rows": 6
      },
      "usage": {
        "a": 3,
        "b": 1,
        "rows": 5
      },
      "risk": {
        "a": 0,
        "b": 0,
        "rows": 4
      },
      "schedule": {
        "a": 1,
        "b": 1,
        "rows": 6
      },
      "situation": {
        "a": 1,
        "b": 4,
        "rows": 7
      },
      "depth": {
        "a": 0,
        "b": 0,
        "rows": 1
      }
    }
  },
  "playoffs": {
    "first": 15,
    "last": 17,
    "assumed": true
  },
  "algo_version": "battle.v1"
};

export const BATTLE_FIXTURE_TEASER = "A clean sweep: the man in the spot wins all 4 horizons and 13 rows of the tape.";
