"""Regenerate the demo build's admin dashboard from the metrics test fixture.

The static demo has no API, so /admin shows web/src/lib/adminMetrics.mock.ts. That file is
tests/test_metrics.py's fixture run through edge/business/metrics.py, so the demo shows
exactly what the tests pin. Run this whenever the report's shape changes:

    uv run python scripts/gen_admin_mock.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web/src/lib/adminMetrics.mock.ts"


def ts_style(body: str) -> str:
    """JSON written the way the committed file reads: bare keys and trailing commas, so a
    regenerate changes only the lines whose numbers moved. A list of numbers stays on one line."""
    num = r"(?:-?[\d.eE+-]+|null)"
    body = re.sub(rf"\[\s*({num}(?:,\s*{num})*)\s*\]", lambda m: "[" + re.sub(r",\s*", ", ", m.group(1)) + "]", body)
    lines = [re.sub(r'^(\s*)"([A-Za-z_$][A-Za-z0-9_$]*)":', r"\1\2:", ln) for ln in body.split("\n")]
    for i in range(len(lines) - 1):
        nxt = lines[i + 1].lstrip()
        if nxt[:1] in ("}", "]") and not lines[i].rstrip().endswith(("{", "[", ",")):
            lines[i] += ","
    return "\n".join(lines)


def main() -> None:
    sys.path.insert(0, str(ROOT / "tests"))
    import test_metrics as t  # noqa: PLC0415 — the fixture lives with its tests
    from edge.business import metrics as m

    start, end = m.resolve_range(None, None, t.NOW)
    report = m.report(t.EVENTS, t.USERS, t.SPEND, t.ACTIVITY, 3, 2, start, end, t.NOW,
                      shares=[{"id": "ab3kx9qz", "views": 5, "created": t.T}])
    body = ts_style(json.dumps(report, indent=2, ensure_ascii=False))
    OUT.write_text(
        "/** Generated by scripts/gen_admin_mock.py from tests/test_metrics.py. Do not edit by hand. */\n"
        'import type { AdminMetrics } from "./types";\n\n'
        f"export const ADMIN_METRICS_FIXTURE: AdminMetrics = {body};\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
