#!/usr/bin/env python3
"""Write web/src/lib/battle.mock.ts: one real Position Battle, from the recorded fixtures.

The demo build has no API, so the battle page needs a payload to draw. Rather than type one
by hand -- which would drift from `edge/engine/battle.py` the first time a row was added --
this runs the engine over the recorded week-2 league (the same arena `tests/test_battle.py`
builds) and writes what it returns. `web/src/lib/mocks.ts` swaps the two men's identities
in for whichever pair the demo asks for. Re-run after changing the engine's output shape.

    uv run python scripts/gen_battle_mock.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
FIX = ROOT / "tests" / "fixtures"
OUT = ROOT / "web" / "src" / "lib" / "battle.mock.ts"


def load(rel: str):
    return json.loads((FIX / rel).read_text())


def main() -> None:
    from edge.connectors.sleeper import build_league
    from edge.data import nfl_stats
    from edge.data.depth_charts import boil
    from edge.data.schedule import bye_weeks
    from edge.engine import battle as B
    from edge.engine import decisions as D
    from edge.engine.values import ros_values

    lg = build_league(load("sleeper/league.json"), load("sleeper/users.json"), load("sleeper/rosters.json"),
                      load("sleeper/players_subset.json"), week=2, projections_raw=load("sleeper/projections_2026_2.json"))
    sched = load("schedule_2026.json")
    charts = boil(load("sleeper/depth_charts.json")["players"])
    log: dict = {}
    for r in load("sleeper/stats/stats_2026_1.json"):
        ln = nfl_stats.to_line(r, 2026)
        log.setdefault(ln.player_id, []).append(ln)
    last = {str(r["player_id"]): nfl_stats.to_line(r, 2025) for r in load("sleeper/stats/stats_2025_season.json")}
    byes = bye_weeks(sched["weeks"])
    ros = ros_values(lg, load("sleeper/projections_2026_season.json"), byes)
    team = lg.teams[0]
    ctx = D.build(lg, team, load("sleeper/matchups_2.json"), sched["games"], charts, log, byes)
    players = load("sleeper/players_subset.json")
    arena = B.Arena(league=lg, team=team, ros=ros, byes=byes, games=sched["games"], charts=charts, log=log,
                    last=last, ctx=ctx)
    labels = B._labels(lg, team)  # noqa: SLF001
    a = next(pid for pid, (_, lab) in labels.items() if lab == "WR2")
    b = next(r["id"] for r in B.options(arena, a)["wire"] if r["position"] == "WR")
    arena.meta = {i: {"age": (players.get(i) or {}).get("age"), "years_exp": (players.get(i) or {}).get("years_exp")}
                  for i in (a, b)}
    battle = B.fight(arena, a, b)
    teaser = B.teaser(battle)
    OUT.write_text(
        "/** Generated by scripts/gen_battle_mock.py from the recorded fixtures. Do not edit by hand. */\n"
        'import type { Battle } from "./types";\n\n'
        f"export const BATTLE_FIXTURE: Battle = {json.dumps(battle, indent=2)};\n\n"
        f"export const BATTLE_FIXTURE_TEASER = {json.dumps(teaser)};\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {battle['a']['name']} vs {battle['b']['name']}, {len(battle['tape'])} rows")


if __name__ == "__main__":
    main()
