import type { Metadata } from "next";
import { LAST_UPDATED } from "../layout";

export const metadata: Metadata = {
  title: "Terms — Edge",
  description: "What Edge promises, what it does not, and the rules for using it.",
};

export default function Terms() {
  return (
    <>
      <h1 className="display text-3xl">Terms of use</h1>
      <p className="mt-1 text-sm text-muted">Last updated {LAST_UPDATED}</p>

      <p className="mt-6">
        Edge reads a fantasy football league you already play in and tells you what we think this
        week&rsquo;s best moves are. Using it means you accept what is on this page.
      </p>

      <h2 className="display mt-8 text-xl">What you get</h2>
      <p className="mt-2">
        Start/sit calls for one team are free. The Waiver Wire Pass, Trade Lab, and Full Report are
        one-time purchases that last the rest of the current NFL season. There is no subscription and
        nothing renews. A season pass ends when the season does.
      </p>

      <h2 className="display mt-8 text-xl">This is advice, not a guarantee</h2>
      <p className="mt-2">
        Every recommendation is a projection, and projections are wrong all the time. We label each
        call with how confident we are and we publish our hit rate, including the weeks we get it
        wrong. A &ldquo;Lock&rdquo; has been right about four times in five. That is not the same as
        being right.
      </p>
      <p className="mt-2">
        You make your own lineup decisions. We are not liable for a loss, a missed playoff spot, or a
        trade that went badly. Edge is for entertainment and is not betting or wagering advice.
      </p>

      <h2 className="display mt-8 text-xl">Your league, your account</h2>
      <p className="mt-2">
        Connect leagues you actually play in. Do not use Edge to interfere with someone else&rsquo;s
        league, and do not connect a league you were asked to stay out of. Keep your sign-in link to
        yourself; anyone who has it can reach your account.
      </p>

      <h2 className="display mt-8 text-xl">Fair use</h2>
      <p className="mt-2">
        Please do not scrape the site, resell the output, run automated requests at volume, or try to
        get at other people&rsquo;s data. We may rate-limit or close an account doing any of that.
        Building your own thing on top of ours needs a conversation first, and we are usually up for
        it.
      </p>

      <h2 className="display mt-8 text-xl">Where the data comes from</h2>
      <p className="mt-2">
        League information comes from Sleeper and ESPN. Projections come from Sleeper, rescored to
        your league&rsquo;s own settings. Player photographs and team marks belong to their owners
        and appear only to identify a player. Edge is not affiliated with, endorsed by, or sponsored
        by the NFL, the NFLPA, Sleeper, ESPN, or Yahoo. If one of those platforms changes or removes
        access, features that depend on it may stop working.
      </p>

      <h2 className="display mt-8 text-xl">Written explanations</h2>
      <p className="mt-2">
        The numbers behind every recommendation come from our own engine. Some written explanations
        are generated by an AI model from those numbers. The model explains the result; it never
        decides it and never invents a figure. It can still phrase something badly, so trust the
        numbers over the prose.
      </p>

      <h2 className="display mt-8 text-xl">Availability</h2>
      <p className="mt-2">
        This is a small operation run by one person during a football season. We aim to be up when
        you need us on a Sunday morning, but there is no uptime guarantee. If an outage costs you a
        week of a pass, email us and we will make it right.
      </p>

      <h2 className="display mt-8 text-xl">Ending it</h2>
      <p className="mt-2">
        You can delete your account whenever you like, which removes your data and your passes. We
        can close an account that breaks these terms. Refunds are on the{" "}
        <a className="underline" href="/legal/refunds">
          refunds page
        </a>
        .
      </p>

      <h2 className="display mt-8 text-xl">Changes</h2>
      <p className="mt-2">
        If these terms change in a way that matters, we will say so by email before the change takes
        effect for anyone who has already paid.
      </p>
    </>
  );
}
